# Generated by Django 5.2 on 2025-07-15 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_ai_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usage_reset_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
