# Generated by Django 5.2 on 2025-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cramsheet',
            name='questions_generated',
            field=models.BooleanField(default=False),
        ),
    ]
