# Generated by Django 5.2 on 2025-04-09 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram_app', '0002_cramsheet_questions_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cram_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cram_app.cramsheet')),
            ],
        ),
    ]
