# Generated by Django 5.2 on 2025-04-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cram_app', '0003_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='correct_answer',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testquestion',
            name='wrong_answers',
            field=models.JSONField(default='default'),
            preserve_default=False,
        ),
    ]
